name = "payday-ap"
main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[vars]
ALLOWED_ORIGIN = "https://payday-ap.pages.dev"
COOKIE_DOMAIN = ""

[[d1_databases]]
binding = "DB"
database_name = "payday-db"
database_id = "0000002c-00000000-000050d2-f8ea308755e142123136259e9aa965a9"
